#!/usr/bin/env ruby

random_number = rand(1..10)

loop do
  print 'Please guess a number between 1 and 10 to see if it equals the random
  number generated by the program:  '
  number_guessed = gets.chomp.to_i

  if number_guessed > random_number
    puts 'Too high'

  elsif number_guessed < random_number
    puts 'Too low'

  else
    puts 'You got it'
    break
  end
end
